  #端口号
    server:
      port: 9010
      servlet:
        session:
          timeout: 28800s
    #数据库的配置信息
    spring:
      datasource:
        url: jdbc:mysql://47.114.7.27:3306/smart?characterEncoding=utf8&useSSL=true #自己的数据库名称
        username: root
        password: 123
        driver-class-name: com.mysql.jdbc.Driver
      jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8